### PR TITLE
create Ontology User pathway

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
@sbello could you take a look at this and revise as you see fit? thanks!

### CODE REVIEW

**Comment by sbello** [comment]
Poking around for other resources we could add

https://github.com/jamesaoverton/obo-tutorial/blob/master/docs/using-and-reusing.md Is this too out of date?

Maybe a bit old but could be a useful publication https://pubmed.ncbi.nlm.nih.gov/25776021/ 

Do you know anything about this site https://www.ontotext.com/knowledge-hub/fundamentals/ could be useful?

**Comment by nicolevasilevsky** [comment]
I think this is an updated version of James' doc:
https://oboacademy.github.io/obook/lesson/ontology-term-use/

The other content looks good, do you to add it on this PR?

**Comment by sierra-moxon** [comment]
Would the page that @nlharris and I are putting together on how LinkML can help users define how ontologies can be used in their organization (and also how LinkML reuses ontologies in its data definition language) be helpful here?

**Comment by nicolevasilevsky** [comment]
From Danielle Welter: 

- [ ] add https://faircookbook.elixir-europe.org/content/recipes/interoperability/selecting-ontologies.html
- [ ] https://faircookbook.elixir-europe.org/content/recipes/interoperability/ontology-alignment-oxo.html

**Comment by shawntanzk** [comment]
In case you need, I have previously tried to capture some resources from around - they are probably a mix of ontology building and use, but in case you need it https://docs.google.com/spreadsheets/d/1KPhLQx_sWjeo5Vn7gvwElVWqbiYCGSRDnBEngNUGb5g/edit#gid=0 please do credit the authors of the documents, I promise them I would if I used it :) 
Hope that helps

**Comment by nicolevasilevsky** [comment]
> Would the page that @nlharris and I are putting together on how LinkML can help users define how ontologies can be used in their organization (and also how LinkML reuses ontologies in its data definition language) be helpful here?

yes please @sierra-moxon. Please add it whenever it is ready.

**Comment by nicolevasilevsky** [comment]
> In case you need, I have previously tried to capture some resources from around - they are probably a mix of ontology building and use, but in case you need it https://docs.google.com/spreadsheets/d/1KPhLQx_sWjeo5Vn7gvwElVWqbiYCGSRDnBEngNUGb5g/edit#gid=0 please do credit the authors of the documents, I promise them I would if I used it :) Hope that helps

Thanks @shawntanzk!

**Comment by sbello** [comment]
From the Mastodon ask:
https://link.springer.com/book/10.1007/978-1-4939-3743-1 ([Marc Robinson-Rechavi](https://mstdn.social/@marcrr@ecoevo.social))

**Comment by nicolevasilevsky** [comment]
@sbello I already merged this PR. Can you edit the page or create a ticket?

**Comment by sbello** [comment]
@nicolevasilevsky new ticket added https://github.com/OBOAcademy/obook/issues/432

**Pull request merged**
