### PR TITLE
Instructions to run the site locally added to readme.md

### PR DESCRIPTION
**Pull request by manulera**
Instructions to run the site locally added to readme.md

### CODE REVIEW

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by nicolevasilevsky** [comment]
Thanks for all of your contributions @manulera!

**Review by matentzn — APPROVED** [review]
This is very cool, thank you!

**Comment by manulera** [comment]
Hello, should this be merged?

**Comment by matentzn** [comment]
Sorry, missed this! Thanks for the ping!

**Pull request merged**
