### PR TITLE
fix to glommed-together lines?

### PR DESCRIPTION
**Pull request by nlharris**
not sure why https://oboacademy.github.io/obook/tutorial/ontogpt/ loses line breaks that look fine in the preview. adding <br/>s that will hopefully help

### CODE REVIEW

**Comment by nlharris** [comment]
also, once this is merged i'm going to do another PR to prominently link to https://oboacademy.github.io/obook/lesson/chatgpt-ontology-curation/ from  ttps://oboacademy.github.io/obook/tutorial/ontogpt/

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
You have to make empty rows so that mkdocs processes this correctly

**Comment by nlharris** [comment]
ok. i was just trying to save whitespace. 😀

**Review by nlharris — COMMENTED** [review]
hmm, the nested bullets that i indicated in the md are also ignored. the obook site uses some unholy combination of md and html, doesn't it? and from a drive-by editor's perspective, it's hard to guess which will win.

**Comment by matentzn** [comment]
Needs 4 spaces for mkdocs: https://oboacademy.github.io/obook/tutorial/ontogpt/

**Pull request merged**
